# Generated by Django 2.2.7 on 2020-09-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('attribute_id', models.PositiveSmallIntegerField(choices=[(1, 'height'), (2, 'weight'), (3, 'heart_rate'), (4, 'calorie')])),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'attribute_values',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('bought_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_devices',
                'unique_together': {('user_id', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=14)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'client'), (1, 'admin')], default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('phone',)},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20)),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, 'height'), (2, 'weight'), (3, 'heart_rate'), (4, 'calorie')], default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'devices',
                'unique_together': {('imei',)},
            },
        ),
    ]
